"""Claude chat layer: the only code in the project that calls the Anthropic API.

See DESIGN.md §3.5. There are exactly two entry points and both are user-initiated:

* :meth:`ClaudeChat.chat_stream` - the web app's ``POST /api/chat`` (the user typed a message);
* :meth:`ClaudeChat.ask` - the CLI ``ask`` command (the user asked a question).

Nothing here (or anywhere else) calls Claude on a timer, on a poll, on a draft-state change or
in a loop. The former per-player research loop (web search) and the automatic on-the-clock
advice were removed because they ran up a large bill; every remaining call is one request per
user action and reports its token usage and an estimated cost.

Everything is optional: when no API key is available :class:`ClaudeChat` reports
``enabled == False``, ``chat_stream`` raises ``RuntimeError`` and ``ask`` returns ``""``. The
``anthropic`` SDK is imported lazily (first real request), so importing this module never
touches the network stack.

Research notes that earlier versions wrote under ``research_dir()/notes/<player_id>.json`` are
still read (:meth:`ClaudeChat.load_notes`) so their red flags and risk numbers keep showing up
in the context text and the projections; nothing writes new ones.

Prompt caching: no ``cache_control`` markers are sent. The chat and ask system prompts are far
below the 1024-token minimum cacheable prefix, so a marker would be silently ignored.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
from pathlib import Path
from typing import Any, Mapping

from ..config import CLAUDE_MODEL, SKILL_POSITIONS, SLOT_ELIGIBILITY, research_dir
from ..models import DraftState, LeagueSettings, Pick, Player, Recommendation, ResearchNote

log = logging.getLogger(__name__)

__all__ = [
    "ClaudeChat",
    "ClaudeResearcher",
    "CHAT_MODEL",
    "CHAT_MAX_TURNS",
    "CHAT_MAX_CHARS",
    "MODEL_PRICES_USD_PER_MTOK",
    "estimate_cost_usd",
    "model_prices",
    "trim_transcript",
    "usage_dict",
    "build_context_text",
    "describe_scoring",
    "describe_roster_slots",
    "UNAVAILABLE_SUMMARY",
]

#: Summary text of a legacy note whose research failed; such notes are ignored in the context text.
UNAVAILABLE_SUMMARY = "(research unavailable)"

#: Number of candidates listed in the context text.
CONTEXT_TOP_N = 8
#: Number of most recent picks shown in the context.
RECENT_PICKS_N = 6

#: Output budget for :meth:`ClaudeChat.ask`.
ASK_MAX_TOKENS = 1500
#: Appended to an ``ask`` answer that hit ``max_tokens``.
TRUNCATION_MARKER = "\n\n[answer truncated: max_tokens reached]"

#: Chat model for the web app (``DRAFTADVISOR_CHAT_MODEL`` overrides it per deployment).
CHAT_MODEL = "claude-opus-5"

#: Transcript limits the web endpoint applies before a request goes out (:func:`trim_transcript`):
#: the newest turns win, so a long chat costs a bounded number of input tokens per message.
CHAT_MAX_TURNS = 40
CHAT_MAX_CHARS = 60_000

#: USD per million tokens (input, output) for the models the app offers.
MODEL_PRICES_USD_PER_MTOK: dict[str, tuple[float, float]] = {
    "claude-opus-5": (5.0, 25.0),
    "claude-sonnet-5": (2.0, 10.0),
}
#: Cache reads are billed at 10 % of the input price, cache writes at 125 %.
CACHE_READ_PRICE_FACTOR = 0.1
CACHE_WRITE_PRICE_FACTOR = 1.25
USAGE_KEYS = ("input_tokens", "output_tokens", "cache_read_input_tokens", "cache_creation_input_tokens")

CHAT_SYSTEM_PROMPT = (
    "You are a fantasy-football draft strategist sitting next to a manager during a live Sleeper draft. "
    "Each user message may begin with a [Live draft context] block: the league scoring, the manager's roster and "
    "open needs, their upcoming pick numbers, the engine's current recommendations (projected league points, "
    "value over replacement, availability at their next pick, tiers, reasons) and any notes with red flags. "
    "Treat that block as the current truth about the draft; it is generated by software, not typed by the user. "
    "Answer the question directly, disagree with the engine when the evidence supports it, quantify trade-offs "
    "(points, tiers, availability), name concrete players, and keep answers short enough to read on a pick clock "
    "unless the user asks for depth. Use plain prose or short bullet lists; no headers."
)

ASK_SYSTEM_PROMPT = (
    "You are an expert fantasy-football draft analyst helping a manager during or before their Sleeper draft. "
    "Use the draft context provided (roster, candidates, projections, notes) as the primary source of truth and "
    "answer the question directly and concisely, with concrete player names and numbers when relevant."
)


# ---------------------------------------------------------------------------
# Small helpers (pure)
# ---------------------------------------------------------------------------


def _describe_error(exc: BaseException) -> str:
    name = type(exc).__name__
    status = getattr(exc, "status_code", None)
    text = str(exc).replace("\n", " ")[:200]
    return f"{name}({status}): {text}" if status else f"{name}: {text}"


def _text_blocks(message: Any) -> list[str]:
    """All non-empty text blocks of a response, in order (tolerates fake objects)."""
    out: list[str] = []
    for block in getattr(message, "content", None) or []:
        if getattr(block, "type", None) == "text":
            text = getattr(block, "text", None)
            if text:
                out.append(str(text))
    return out


def _response_text(message: Any) -> str:
    return "\n".join(_text_blocks(message)).strip()


def _usage_int(usage: Any, key: str) -> int | None:
    value = usage.get(key) if isinstance(usage, Mapping) else getattr(usage, key, None)
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def usage_dict(usage: Any) -> dict[str, int | None]:
    """The four token counters of an SDK ``Usage`` object (or a dict) as a plain dict."""
    return {key: _usage_int(usage, key) for key in USAGE_KEYS}


def model_prices(model: str | None) -> tuple[float, float] | None:
    """(input, output) USD per million tokens for ``model`` (exact id, or a dated variant of one)."""
    name = (model or "").strip().lower()
    if not name:
        return None
    hit = MODEL_PRICES_USD_PER_MTOK.get(name)
    if hit is not None:
        return hit
    for key, prices in MODEL_PRICES_USD_PER_MTOK.items():
        if name.startswith(key):
            return prices
    return None


def estimate_cost_usd(model: str | None, usage: Any) -> float | None:
    """Estimated USD cost of one response from its ``usage`` (dict or SDK object).

    ``input_tokens`` / ``output_tokens`` are billed at the list price, ``cache_read_input_tokens``
    at 10 % of the input price and ``cache_creation_input_tokens`` at 125 %. ``None`` when the
    model is not in :data:`MODEL_PRICES_USD_PER_MTOK` or the usage carries no token counts.
    """
    prices = model_prices(model)
    if prices is None or usage is None:
        return None
    counts = usage_dict(usage)
    if counts["input_tokens"] is None and counts["output_tokens"] is None:
        return None
    in_price, out_price = prices
    total = (counts["input_tokens"] or 0) * in_price + (counts["output_tokens"] or 0) * out_price
    total += (counts["cache_read_input_tokens"] or 0) * in_price * CACHE_READ_PRICE_FACTOR
    total += (counts["cache_creation_input_tokens"] or 0) * in_price * CACHE_WRITE_PRICE_FACTOR
    return round(total / 1_000_000.0, 6)


def _turn_len(turn: Mapping[str, Any]) -> int:
    return len(str(turn.get("content") or "")) if isinstance(turn, Mapping) else 0


def trim_transcript(messages: list[dict[str, Any]], *, max_turns: int = CHAT_MAX_TURNS,
                    max_chars: int = CHAT_MAX_CHARS) -> list[dict[str, Any]]:
    """The newest turns of ``messages`` that fit within ``max_turns`` and ``max_chars`` of content.

    Turns are dropped oldest first; the last turn is always kept (the caller rejects a single turn
    that is too long on its own). Leading assistant turns left over after the cut are dropped too,
    so the transcript still starts with a user turn as the API requires.
    """
    kept: list[dict[str, Any]] = []
    total = 0
    for turn in reversed(messages):
        size = _turn_len(turn)
        if kept and (len(kept) >= max_turns or total + size > max_chars):
            break
        kept.append(turn)
        total += size
    kept.reverse()
    while kept and isinstance(kept[0], Mapping) and kept[0].get("role") != "user":
        kept.pop(0)
    return kept


def _player_line(pl: Player, points: float | None = None) -> str:
    bits = [f"{pl.name} ({pl.position}, {pl.team or 'FA'}"]
    if pl.bye_week:
        bits.append(f", bye {pl.bye_week}")
    bits.append(")")
    if points is not None:
        bits.append(f" {points:.0f} pts")
    if pl.injury_status and pl.injury_status not in ("NA", "Healthy"):
        bits.append(f" [{pl.injury_status}]")
    return "".join(bits)


def describe_scoring(league: LeagueSettings | None) -> str:
    """One-line human description of the league scoring."""
    if league is None:
        return "scoring unknown (assume half-PPR)"
    s = league.scoring_settings or {}

    def g(key: str, default: float = 0.0) -> float:
        try:
            return float(s.get(key, default) or 0.0)
        except (TypeError, ValueError):
            return default

    parts = [f"{league.scoring_type.replace('_', '-').upper()} (rec {g('rec'):g})"]
    parts.append(f"pass TD {g('pass_td', 4):g}, pass yd {g('pass_yd', 0.04):g}/yd, INT {g('pass_int', -1):g}")
    parts.append(f"rush/rec TD {g('rush_td', 6):g}/{g('rec_td', 6):g}")
    if league.te_premium:
        parts.append(f"TE premium +{league.te_premium:g}/rec")
    for key, label in (("bonus_rec_wr", "WR bonus"), ("bonus_rec_rb", "RB bonus"), ("pass_2pt", "2pt pass")):
        if g(key):
            parts.append(f"{label} {g(key):g}")
    if league.is_superflex:
        parts.append("SUPERFLEX")
    return "; ".join(parts)


def describe_roster_slots(league: LeagueSettings | None) -> str:
    """Compact roster-shape description, e.g. 'QB, RB x2, WR x2, TE, FLEX(RB/WR/TE), K, DEF; bench 6'."""
    if league is None:
        return "starting slots unknown"
    counts: dict[str, int] = {}
    for slot in league.starting_slots:
        counts[slot] = counts.get(slot, 0) + 1
    items = []
    for slot, n in counts.items():
        elig = SLOT_ELIGIBILITY.get(slot)
        label = slot
        if elig and len(elig) > 1:
            label = f"{slot}({'/'.join(sorted(elig, key=SKILL_POSITIONS.index))})"
        items.append(f"{label} x{n}" if n > 1 else label)
    extra = f"; bench {league.bench_slots}"
    ir = league.roster_positions.count("IR")
    if ir:
        extra += f", IR {ir}"
    return ", ".join(items) + extra


# ---------------------------------------------------------------------------
# Context text (shared by chat and ask)
# ---------------------------------------------------------------------------


def _pick_name(pk: Pick, players: dict[str, Player]) -> str:
    pl = players.get(pk.player_id)
    if pl is not None:
        return f"{pl.name} ({pl.position})"
    pos = pk.position
    return f"{pk.player_name} ({pos})" if pos else pk.player_name


def _roster_section(state: DraftState, rec: Recommendation | None, players: dict[str, Player]) -> list[str]:
    lines: list[str] = ["MY ROSTER:"]
    summary = rec.my_roster if rec is not None else None
    if summary is not None:
        by_pos: dict[str, list[Player]] = {}
        for pl in summary.players:
            by_pos.setdefault(pl.position, []).append(pl)
        proj_by_id = {pv.player_id: pv.projection for pv in (rec.best_overall if rec else [])}
        if not summary.players:
            lines.append("  (empty)")
        for pos in SKILL_POSITIONS:
            group = by_pos.get(pos)
            if not group:
                continue
            names = ", ".join(_player_line(pl, proj_by_id[pl.player_id].points if pl.player_id in proj_by_id else None)
                              for pl in group)
            lines.append(f"  {pos}: {names}")
        for pos, group in by_pos.items():
            if pos not in SKILL_POSITIONS:
                lines.append(f"  {pos}: {', '.join(pl.name for pl in group)}")
        slots = ", ".join(
            f"{slot} {summary.starters_filled.get(slot, 0)}/{summary.starters_filled.get(slot, 0) + n}"
            for slot, n in summary.open_starters.items()
        )
        if slots:
            lines.append(f"  Starting slots filled: {slots}")
        needs = [slot for slot, n in summary.open_starters.items() if n > 0]
        lines.append(f"  Open needs: {', '.join(needs) if needs else 'none (bench depth only)'}")
        clashes = [f"week {w} x{n}" for w, n in sorted(summary.bye_weeks.items()) if n >= 2]
        if clashes:
            lines.append(f"  Bye clashes among starters: {', '.join(clashes)}")
        if summary.lineup_points:
            lines.append(f"  Projected lineup points so far: {summary.lineup_points:.0f}")
        return lines
    mine = state.my_picks()
    if not mine:
        lines.append("  (empty)")
    for pk in mine:
        lines.append(f"  R{pk.round}: {_pick_name(pk, players)}")
    return lines


def _candidate_lines(rec: Recommendation, notes: Mapping[str, ResearchNote] | None) -> list[str]:
    lines = [f"TOP {min(CONTEXT_TOP_N, len(rec.best_overall))} CANDIDATES (by model score):"]
    for i, pv in enumerate(rec.best_overall[:CONTEXT_TOP_N], start=1):
        pl, pr = pv.player, pv.projection
        head = (
            f"  {i}. {_player_line(pl)} - {pr.points:.0f} pts, VORP {pv.vorp:+.0f}, "
            f"avail@next {pv.availability_next * 100:.0f}%, tier {pv.tier}, "
            f"pos rank {pv.pos_rank}, score {pv.score:.0f}"
        )
        if pl.adp:
            head += f", ADP {pl.adp:.0f}"
        lines.append(head)
        if pv.reasons:
            lines.append(f"     why: {'; '.join(pv.reasons[:4])}")
        if pv.warnings:
            lines.append(f"     warn: {'; '.join(pv.warnings[:3])}")
        note = (notes or {}).get(pl.player_id)
        if note is not None and note.summary and note.summary != UNAVAILABLE_SUMMARY:
            flags = getattr(note, "red_flags", None) or []
            off = getattr(note, "offfield_risk", 0.0) or 0.0
            extra = f", off-field risk {off:.1f}" if off else ""
            lines.append(
                f"     note: {note.summary} (injury risk {note.injury_risk:.1f}, role certainty {note.role_certainty:.1f}{extra})"
            )
            if flags:
                lines.append("     RED FLAGS: " + "; ".join(flags[:6]))
    return lines


def _position_lines(rec: Recommendation) -> list[str]:
    lines = ["POSITION OUTLOOK:"]
    for pos in SKILL_POSITIONS:
        adv = rec.by_position.get(pos)
        if adv is None:
            continue
        best = adv.candidates[0] if adv.candidates else None
        best_txt = f" best: {best.player.name} {best.projection.points:.0f} pts" if best else ""
        lines.append(f"  {pos}: {adv.action} - {adv.rationale}{best_txt}")
    return lines


def _recent_picks_lines(state: DraftState, players: dict[str, Player]) -> list[str]:
    recent = sorted(state.picks, key=lambda p: p.pick_no)[-RECENT_PICKS_N:]
    lines = [f"LAST {len(recent)} PICKS:"]
    if not recent:
        lines.append("  (none yet)")
    for pk in recent:
        lines.append(f"  #{pk.pick_no} {state.slot_label(pk.draft_slot)}: {_pick_name(pk, players)}")
    return lines


def build_context_text(
    state: DraftState,
    rec: Recommendation | None,
    players: dict[str, Player],
    notes: Mapping[str, ResearchNote] | None,
) -> str:
    """Compact plain-text picture of the draft for Claude (roster, needs, candidates, picks, pressure)."""
    draft = state.draft
    league = state.league
    lines: list[str] = []
    league_name = league.name if league is not None else "League"
    on_clock = state.on_the_clock_slot
    header = (
        f"{league_name}: round {state.current_round} of {draft.rounds}, pick #{state.next_pick_no} "
        f"of {draft.total_picks}, {draft.teams} teams"
    )
    if on_clock is not None:
        header += f"; on the clock: {state.slot_label(on_clock)}"
    lines.append(header)
    if state.my_slot is not None:
        fut = state.my_future_picks()
        mine = f"I am slot {state.my_slot} ({state.slot_label(state.my_slot)})."
        if state.is_my_turn:
            mine += " IT IS MY PICK NOW."
        if fut:
            nxt = ", ".join(f"#{p}" for p in fut[:3])
            until = state.picks_until_my_turn
            mine += f" My next picks: {nxt}" + (f" ({until} picks away)." if until else ".")
        lines.append(mine)
    lines.append("")
    lines.extend(_roster_section(state, rec, players))
    lines.append("")
    if rec is not None:
        lines.extend(_candidate_lines(rec, notes))
        lines.append("")
        lines.extend(_position_lines(rec))
        lines.append("")
    lines.extend(_recent_picks_lines(state, players))
    if rec is not None and rec.position_pressure:
        pressure = ", ".join(
            f"{pos} {rec.position_pressure[pos]:.1f}" for pos in SKILL_POSITIONS if pos in rec.position_pressure
        )
        lines.append("")
        lines.append(f"EXPECTED PICKS BY POSITION BEFORE MY NEXT TURN: {pressure}")
    if rec is not None and rec.notes:
        lines.append("NOTES: " + " | ".join(rec.notes[:5]))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Chat client
# ---------------------------------------------------------------------------


class ClaudeChat:
    """User-initiated Claude access (web chat + CLI ask). Safe to construct anywhere; does nothing when disabled."""

    #: Upper bound for :meth:`ask`.
    ask_timeout_s: float = 120.0

    def __init__(
        self,
        api_key: str | None = None,
        model: str = CLAUDE_MODEL,
        cache_dir: Path | None = None,
        client: Any = None,
    ) -> None:
        self._api_key = api_key or os.environ.get("ANTHROPIC_API_KEY") or None
        #: Model used by :meth:`ask` (``chat_stream`` takes its own ``model`` argument).
        self.model = model or CLAUDE_MODEL
        self._cache_dir = Path(cache_dir) if cache_dir is not None else None
        self._client = client
        self._sdk_unavailable = False
        self.last_error: str | None = None
        #: Token usage / estimated cost of the last completed request (``ask`` or ``chat_stream``).
        self.last_usage: dict[str, int | None] | None = None
        self.last_cost_usd: float | None = None
        self.request_count = 0

    # -- state ----------------------------------------------------------------
    @property
    def enabled(self) -> bool:
        if self._sdk_unavailable:
            return False
        return self._client is not None or bool(self._api_key)

    @property
    def notes_dir(self) -> Path:
        base = self._cache_dir if self._cache_dir is not None else research_dir()
        return base / "notes"

    def _get_client(self) -> Any | None:
        """Lazily build the AsyncAnthropic client (imports the SDK on first use)."""
        if self._client is not None:
            return self._client
        if not self._api_key or self._sdk_unavailable:
            return None
        try:
            import anthropic  # noqa: WPS433 (lazy import by design)
        except Exception as exc:  # pragma: no cover - SDK missing/broken
            log.warning("anthropic SDK unavailable, Claude layer disabled: %s", _describe_error(exc))
            self._sdk_unavailable = True
            return None
        self._client = anthropic.AsyncAnthropic(api_key=self._api_key, max_retries=2)
        return self._client

    def _record_usage(self, model: str | None, response: Any) -> None:
        self.request_count += 1
        usage = getattr(response, "usage", None)
        self.last_usage = usage_dict(usage) if usage is not None else None
        self.last_cost_usd = estimate_cost_usd(model, self.last_usage) if self.last_usage else None

    # -- legacy notes on disk ---------------------------------------------------
    def load_notes(self) -> dict[str, ResearchNote]:
        """Read every note left by earlier research runs from ``notes_dir`` (corrupt files are skipped).

        Read-only: nothing in the project writes notes any more.
        """
        out: dict[str, ResearchNote] = {}
        d = self.notes_dir
        if not d.is_dir():
            return out
        for path in sorted(d.glob("*.json")):
            try:
                with open(path, encoding="utf-8") as fh:
                    note = ResearchNote.from_dict(json.load(fh))
            except Exception as exc:
                log.warning("skipping corrupt research note %s: %s", path.name, _describe_error(exc))
                continue
            out[note.player_id] = note
        return out

    # -- web chat -----------------------------------------------------------------
    async def chat_stream(self, messages: list[dict[str, Any]], context_text: str, *, model: str | None = None,
                          max_tokens: int = 2000, system: str | None = None):
        """Stream a chat answer (text deltas) with the live draft context injected into the last user turn.

        ``messages`` is the browser-held transcript ([{"role": "user"|"assistant", "content": str}, ...]).
        Yields text chunks; the final yield is a dict ``{"done": True, "stop_reason", "model", "usage": {...},
        "cost_usd": float|None}``. Raises SDK errors to the caller (the web layer turns them into an SSE
        error event). One request per call; never called without a user message.
        """
        client = self._get_client()
        if client is None:
            raise RuntimeError("Claude is disabled (no API key)")
        model = model or os.environ.get("DRAFTADVISOR_CHAT_MODEL") or CHAT_MODEL
        convo: list[dict[str, Any]] = []
        for m in messages:
            role = m.get("role")
            text = str(m.get("content") or "").strip()
            if role not in ("user", "assistant") or not text:
                continue
            if convo and convo[-1]["role"] == role:
                convo[-1]["content"] += "\n\n" + text
            else:
                convo.append({"role": role, "content": text})
        if not convo or convo[-1]["role"] != "user":
            raise ValueError("the last message must be from the user")
        if context_text:
            convo[-1] = {"role": "user", "content": f"[Live draft context]\n{context_text}\n\n[Question]\n{convo[-1]['content']}"}
        kwargs: dict[str, Any] = dict(
            model=model, max_tokens=max_tokens, system=system or CHAT_SYSTEM_PROMPT, messages=convo,
            output_config={"effort": "medium"},
        )
        async with client.messages.stream(**kwargs) as stream:
            async for text in stream.text_stream:
                if text:
                    yield text
            final = await stream.get_final_message()
        served = getattr(final, "model", None) or model
        self._record_usage(served, final)
        cost = self.last_cost_usd
        if cost is None and self.last_usage:
            cost = estimate_cost_usd(model, self.last_usage)      # the served id is not in the price table
        yield {"done": True, "stop_reason": getattr(final, "stop_reason", None), "model": served,
               "usage": dict(self.last_usage or usage_dict(None)), "cost_usd": cost}

    # -- CLI ask ------------------------------------------------------------------
    async def ask(self, question: str, context_text: str) -> str:
        """Free-form question with draft context. Returns "" when disabled or on error
        (``last_error`` then holds the reason). ``last_usage`` / ``last_cost_usd`` describe the request."""
        if not self.enabled:
            return ""
        client = self._get_client()
        if client is None:
            return ""
        content = f"{context_text.strip()}\n\nQUESTION: {question.strip()}" if context_text else question.strip()
        try:
            response = await asyncio.wait_for(
                client.messages.create(
                    model=self.model,
                    max_tokens=ASK_MAX_TOKENS,
                    system=[{"type": "text", "text": ASK_SYSTEM_PROMPT}],
                    messages=[{"role": "user", "content": content}],
                    output_config={"effort": "medium"},
                ),
                self.ask_timeout_s,
            )
            self._record_usage(getattr(response, "model", None) or self.model, response)
        except asyncio.TimeoutError:
            self.last_error = "timeout"
            log.warning("Claude ask timed out")
            return ""
        except Exception as exc:
            self.last_error = _describe_error(exc)
            log.warning("Claude ask failed: %s", self.last_error)
            return ""
        stop = getattr(response, "stop_reason", None)
        if stop == "refusal":
            self.last_error = "refusal"
            return ""
        text = _response_text(response)
        if stop == "max_tokens":
            self.last_error = f"answer truncated (stop_reason=max_tokens at {ASK_MAX_TOKENS} tokens)"
            log.warning("Claude ask hit max_tokens; answer truncated")
            if not text:
                return ""
            text += TRUNCATION_MARKER
        return text


#: Backwards-compatible alias (the class used to research players as well).
ClaudeResearcher = ClaudeChat
